site_name: Youtube Pydantic Models
site_description: Use Pydantic models to work with the YouTube API.
site_author: fedeegmz

repo_name: fedeegmz/youtube-pydantic-models
repo_url: https://github.com/fedeegmz/youtube-pydantic-models

theme:
  name: dracula
  locale: en

nav:
  - Home: index.md
  - Youtube Client: youtube_client.md
  - Models:
    - Channel: models/channel.md
    - Playlist: models/playlist.md
    - Video: models/video.md
    - Search: models/search.md
