exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4

target-version = "py313"

[lint]
preview = true
select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "C4",
    "COM",
    "E",
    "F",
    "FAST",
    "FURB",
    "I",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PIE",
    "PL",
    "PYI",
    "PT",
    "Q",
    "RET",
    "RUF",
    "S",
    "SLF",
    "TID",
    "UP",
    "W",
]
ignore = [
    "N818",
]

fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["F403", "PLC0414"]
"main.py" = ["PLR2004", "S113", "E501", "A002", "B008"]
"tests/*.py" = ["ANN001", "ANN201", "FURB101", "PLW1514", "PLR6301", "PLR2004", "S101", "E501", "E722"]
"samples/*.py" = ["RET503", "RET504", "ANN001"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

docstring-code-format = false
docstring-code-line-length = "dynamic"
